### ISSUE TITLE
Mac python app does not work with latest pySerial from pip

### ISSUE THREAD

**Issue by macostea** [dakota-mewt/mewt#3]
```
Traceback (most recent call last):
  File "mewt/mewt.py", line 12, in <module>
    ser.write("101")
  File "mewt/venv/lib/python3.9/site-packages/serial/serialposix.py", line 616, in write
    d = to_bytes(data)
  File "mewt/venv/lib/python3.9/site-packages/serial/serialutil.py", line 65, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
```

mewt code from master,
pyserial version: pyserial-3.5-py2.py3-none-any.whl
Python 3.9.2

This is easily fixed by replacing all instances of `ser.write("string")` with `ser.write(b"string")`. I can open a PR for it soon.

**Comment by dakota-mewt** [comment]
Hi @macostea,

Yes, please and thank you!  I have very little exposure to Mac/Python.  I only have access to a single Mac (2012 MacMini).  After I got it working for the PC, I tried to make it work in the Mac and was able to get it working.  But I wasn't able to test out any scenarios beyond the basic one.
